### ISSUE TITLE
AttributeError: module 'importlib' has no attribute 'util'

### ISSUE THREAD

**Issue by Python3-8** [romkatv/powerlevel10k#1210]
I just finished configuring Powerlevel10k and I get a Python error:
```py
Traceback (most recent call last):
  File "/opt/google-cloud-sdk/lib/gcloud.py", line 104, in <module>
    main()
  File "/opt/google-cloud-sdk/lib/gcloud.py", line 62, in main
    from googlecloudsdk.core.util import encoding
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/__init__.py", line 23, in <module>
    from googlecloudsdk.core.util import importing
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/util/importing.py", line 23, in <module>
    import imp
  File "/usr/lib/python3.9/imp.py", line 23, in <module>
    from importlib import util
  File "/usr/lib/python3.9/importlib/util.py", line 2, in <module>
    from . import abc
  File "/usr/lib/python3.9/importlib/abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "/usr/lib/python3.9/typing.py", line 26, in <module>
    import re as stdlib_re  # Avoid confusion with the re we export.
  File "/usr/lib/python3.9/re.py", line 124, in <module>
    import enum
  File "/opt/google-cloud-sdk/lib/third_party/enum/__init__.py", line 26, in <module>
    spec = importlib.util.find_spec('enum')
AttributeError: module 'importlib' has no attribute 'util'
```

**Comment by romkatv** [comment]
This isn't coming from powerlevel10k. See https://github.com/kubernetes/kubectl/issues/970 for potential fixes.
