### ISSUE TITLE
Sometimes pastes enormous amount of same characters

### ISSUE THREAD

**Issue by ratijas** [romkatv/powerlevel10k#1610]
### SUMMARY

Sometimes when switching back (focusing) to a Konsole window, all of a sudden it gets flooded / filled with same characters as if they were typed in / pasted.

![konsole + zsh = wwwwwwwwwwwwwwwwwwwwwww](https://user-images.githubusercontent.com/6737986/138447197-786a8c1d-3bc7-430f-aa0d-91268f2d79e1.jpg)

### STEPS TO REPRODUCE

I don't know of any reliable way to trigger this glitch, however I recall it usually happens under these circumstances:

1. Launch Konsole, with my zsh profile
2. Do something
3. Focus away from Konsole
4. Work with other apps
5. Focus back into Konsole window
6. Type any key

### OBSERVED RESULT

Boom! The window is flooded with the same character as if it was pressed and held for some time, or typed in repeatedly many times. It seems that amount of characters "pasted" vs. time is a linear dependency.

### EXPECTED RESULT

This shouldn't be happening.

### SOFTWARE/OS VERSIONS

Operating System: Arch Linux
KDE Plasma Version: 5.23.80
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.14.12-arch1-1 (64-bit)
Graphics Platform: X11

zsh: 5.8-1
zsh-completions: 0.33.0-1
zsh-syntax-highlighting: 0.7.1-1
zsh-theme-powerlevel10k-git: r3923.0a1946b-1

### ADDITIONAL INFORMATION

Not sure if it is a bug in Konsole, zsh, or my particular zsh setup.

https://bugs.kde.org/show_bug.cgi?id=444234

**Comment by ratijas** [comment]
Hi, just keeping you posted that it happens much less often lately. But this time something funny happened:

 
![Screenshot_20230830_222806](https://github.com/romkatv/powerlevel10k/assets/6737986/513dcf8e-33cc-4c7a-a7de-496f23c4f7ac)

zsh crashed O.o

which suggests that it is indeed upstream's fault after all.

For the record, here's a stacktrace:

<details>
<summary>coredumpctl gdb zsh</summary>

```
❯ coredumpctl gdb zsh
           PID: 2409 (zsh)
           UID: 1000 (ratijas)
           GID: 1000 (ratijas)
        Signal: 6 (ABRT)
     Timestamp: Wed 2023-08-30 22:26:40 MSK (4min 20s ago)
  Command Line: /bin/zsh
    Executable: /usr/bin/zsh
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.kde.konsole-4dd1c690f24b4a4c858ca13a0edfd707.scope
          Unit: user@1000.service
     User Unit: app-org.kde.konsole-4dd1c690f24b4a4c858ca13a0edfd707.scope
         Slice: user-1000.slice
     Owner UID: 1000 (ratijas)
       Boot ID: ff710240578a4734b8126a0fb9d9ec24
    Machine ID: 01cb509b8fa644f9983f3f3d34b184c7
      Hostname: orange
       Storage: /var/lib/systemd/coredump/core.zsh.1000.ff710240578a4734b8126a0fb9d9ec24.2409.1693423600000000.zst (present)
  Size on Disk: 1.4M
       Message: Process 2409 (zsh) of user 1000 dumped core.
                
                Stack trace of thread 2409:
                #0  0x00007fe87dc8e83c n/a (libc.so.6 + 0x8e83c)
                #1  0x00007fe87dc3e668 raise (libc.so.6 + 0x3e668)
                #2  0x00007fe87dc264b8 abort (libc.so.6 + 0x264b8)
                #3  0x00007fe87dc27390 n/a (libc.so.6 + 0x27390)
                #4  0x00007fe87dc987b7 n/a (libc.so.6 + 0x987b7)
                #5  0x00007fe87dc9ac59 n/a (libc.so.6 + 0x9ac59)
                #6  0x00007fe87dc9d353 free (libc.so.6 + 0x9d353)
                #7  0x0000556500bbc5ea freeeprog (zsh + 0x9d5ea)
                #8  0x0000556500b61e47 execode (zsh + 0x42e47)
                #9  0x0000556500bc70d7 n/a (zsh + 0xa80d7)
                #10 0x0000556500bc77a6 dotrap (zsh + 0xa87a6)
                #11 0x0000556500bc801b zhandler (zsh + 0xa901b)
                #12 0x0000556500bc76ec dotrap (zsh + 0xa86ec)
                #13 0x0000556500bc801b zhandler (zsh + 0xa901b)
                #14 0x00007fe87d7c6ea5 getbyte (zle.so + 0x19ea5)
                #15 0x00007fe87d7c7ca1 getkeymapcmd (zle.so + 0x1aca1)
                #16 0x00007fe87d7ca7f9 getkeycmd (zle.so + 0x1d7f9)
                #17 0x00007fe87d7cd7bd zlecore (zle.so + 0x207bd)
                #18 0x00007fe87d7ce5c4 zleread (zle.so + 0x215c4)
                #19 0x0000556500b85e34 zleentry (zsh + 0x66e34)
                #20 0x0000556500b866a6 ingetc (zsh + 0x676a6)
                #21 0x0000556500b794b4 n/a (zsh + 0x5a4b4)
                #22 0x0000556500b9428f n/a (zsh + 0x7528f)
                #23 0x0000556500bb70a8 parse_event (zsh + 0x980a8)
                #24 0x0000556500b7f9b6 loop (zsh + 0x609b6)
                #25 0x0000556500b87e05 zsh_main (zsh + 0x68e05)
                #26 0x0000556500b360de main (zsh + 0x170de)
                #27 0x00007fe87dc27cd0 n/a (libc.so.6 + 0x27cd0)
                #28 0x00007fe87dc27d8a __libc_start_main (libc.so.6 + 0x27d8a)
                #29 0x0000556500b36105 _start (zsh + 0x17105)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/zsh...
Reading symbols from /home/ratijas/.cache/debuginfod_client/2ff216260a1ca2704cf769eb1463f4f2453ce81e/debuginfo...                                       
[New LWP 2409]
[Thread debugging using libthread_db enabled]                                                                                                           
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/bin/zsh'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;                                                                 
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007fe87dc8e8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007fe87dc3e668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fe87dc264b8 in __GI_abort () at abort.c:79
#4  0x00007fe87dc27390 in __libc_message (fmt=fmt@entry=0x7fe87dda3550 "%s\n") at ../sysdeps/posix/libc_fatal.c:150
#5  0x00007fe87dc987b7 in malloc_printerr (str=str@entry=0x7fe87dda6550 "free(): double free detected in tcache 2") at malloc.c:5765
#6  0x00007fe87dc9ac59 in _int_free (av=0x7fe87de3eac0 <main_arena>, p=<optimized out>, have_lock=have_lock@entry=0) at malloc.c:4534
#7  0x00007fe87dc9d353 in __GI___libc_free (mem=<optimized out>) at malloc.c:3391
#8  0x0000556500bbc5ea in zfree (sz=<optimized out>, p=<optimized out>) at /usr/src/debug/zsh/zsh-5.9/Src/mem.c:1869
#9  freeeprog (p=0x556501cad9b0) at /usr/src/debug/zsh/zsh-5.9/Src/parse.c:2821
#10 freeeprog (p=0x556501cad9b0) at /usr/src/debug/zsh/zsh-5.9/Src/parse.c:2804
#11 0x0000556500b61e47 in execode (p=0x556501cad9b0, dont_change_job=1, exiting=0, context=0x556500beeb24 "trap")
    at /usr/src/debug/zsh/zsh-5.9/Src/exec.c:1223
#12 0x0000556500bc70d7 in dotrapargs (sig=sig@entry=2, sigtr=0x556500c148c8 <sigtrapped+8>, sigfn=sigfn@entry=0x556501cad9b0)
    at /usr/src/debug/zsh/zsh-5.9/Src/signals.c:1383
#13 0x0000556500bc77a6 in dotrap (sig=sig@entry=2) at /usr/src/debug/zsh/zsh-5.9/Src/signals.c:1489
#14 0x0000556500bc801b in handletrap (sig=2) at /usr/src/debug/zsh/zsh-5.9/Src/signals.c:1204
#15 handletrap (sig=2) at /usr/src/debug/zsh/zsh-5.9/Src/signals.c:1185
#16 zhandler (sig=2) at /usr/src/debug/zsh/zsh-5.9/Src/signals.c:671
#17 0x0000556500bc76ec in dotrap (sig=sig@entry=2) at /usr/src/debug/zsh/zsh-5.9/Src/signals.c:1484
#18 0x0000556500bc801b in handletrap (sig=2) at /usr/src/debug/zsh/zsh-5.9/Src/signals.c:1204
#19 handletrap (sig=2) at /usr/src/debug/zsh/zsh-5.9/Src/signals.c:1185
#20 zhandler (sig=2) at /usr/src/debug/zsh/zsh-5.9/Src/signals.c:671
#21 0x00007fe87d7c6ea5 in getbyte (do_keytmout=do_keytmout@entry=0, timeout=timeout@entry=0x0, full=full@entry=1)
    at /usr/src/debug/zsh/zsh-5.9/Src/Zle/zle_main.c:883
#22 0x00007fe87d7c7ca1 in getkeybuf (w=<optimized out>) at /usr/src/debug/zsh/zsh-5.9/Src/Zle/zle_keymap.c:1696
#23 getkeymapcmd (km=0x5565018d4ee0, funcp=funcp@entry=0x7ffc24329850, strp=strp@entry=0x7ffc24329848)
    at /usr/src/debug/zsh/zsh-5.9/Src/Zle/zle_keymap.c:1607
#24 0x00007fe87d7ca7f9 in getkeycmd () at /usr/src/debug/zsh/zsh-5.9/Src/Zle/zle_keymap.c:1725
#25 0x00007fe87d7cd7bd in zlecore () at /usr/src/debug/zsh/zsh-5.9/Src/Zle/zle_main.c:1134
#26 0x00007fe87d7ce5c4 in zleread (lp=<optimized out>, rp=<optimized out>, flags=<optimized out>, context=0, init=0x7fe87d7ed39a "zle-line-init", 
    finish=0x7fe87d7ed38a "zle-line-finish") at /usr/src/debug/zsh/zsh-5.9/Src/Zle/zle_main.c:1356
#27 0x0000556500b85e34 in zleentry (cmd=cmd@entry=1) at /usr/src/debug/zsh/zsh-5.9/Src/init.c:1631
#28 0x0000556500b866a6 in inputline () at /usr/src/debug/zsh/zsh-5.9/Src/input.c:424
#29 ingetc () at /usr/src/debug/zsh/zsh-5.9/Src/input.c:357
#30 ingetc () at /usr/src/debug/zsh/zsh-5.9/Src/input.c:321
#31 0x0000556500b794b4 in ihgetc () at /usr/src/debug/zsh/zsh-5.9/Src/hist.c:415
#32 0x0000556500b9428f in gettok () at /usr/src/debug/zsh/zsh-5.9/Src/lex.c:622
#33 zshlex () at /usr/src/debug/zsh/zsh-5.9/Src/lex.c:275
#34 0x0000556500bb70a8 in zshlex () at /usr/src/debug/zsh/zsh-5.9/Src/lex.c:268
#35 parse_event (endtok=37) at /usr/src/debug/zsh/zsh-5.9/Src/parse.c:615
#36 0x0000556500b7f9b6 in loop (toplevel=toplevel@entry=1, justonce=justonce@entry=0) at /usr/src/debug/zsh/zsh-5.9/Src/init.c:150
#37 0x0000556500b87e05 in zsh_main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/zsh/zsh-5.9/Src/init.c:1794
#38 0x0000556500b360de in main (argc=<optimized out>, argv=<optimized out>) at ./main.c:93
```

</details>

…unless something from downstream threw so much data at zsh that its parser crashed. I have virtually no idea what is going on in zsh code base.
