### ISSUE TITLE
error in yarn/npm workspaces BREAKS terminal init

### ISSUE THREAD

**Issue by addlistener** [romkatv/powerlevel10k#2394]
```
Last login: Wed Jul 26 14:37:51 on ttys011
Happy Hacking!
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aaa/.npm/_logs/2023-07-26T06_48_21_939Z-debug-0.log
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v18.16.0 --silent` to unset it.
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aaa/.npm/_logs/2023-07-26T06_48_23_590Z-debug-0.log
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v18.16.0 --silent` to unset it.
```

It works fine in a normal git repo. But fails when I init a new tab in a npm/yarn monorepo (yarn workspaces)

The error breaks a lot of normal commands. For ex
```
yarn build                                                                                                  ✔ │ base  │ system  │ 14:53:10 
ERROR: build is not COMMAND nor fully qualified CLASSNAME.
Usage: yarn [OPTIONS] SUBCOMMAND [SUBCOMMAND OPTIONS]
 or    yarn [OPTIONS] CLASSNAME [CLASSNAME OPTIONS]
  where CLASSNAME is a user-provided Java class

  OPTIONS is none or any of:

--buildpaths                       attempt to add class files from build tree
--config dir                       Hadoop config directory
--daemon (start|status|stop)       operate on a daemon
--debug                            turn on shell script debug mode
--help                             usage information
```

I have to disable p10k because I cannot find things such as `npm config` in the p10k codebase.

---------

The tailing of log `/Users/aaa/.npm/_logs/2023-07-26T06_48_23_590Z-debug-0.log`
```
24 timing config:load:flatten Completed in 2ms
25 timing npm:load:display Completed in 2ms
26 verbose logfile logs-max:10 dir:/Users/aaa/.npm/_logs/2023-07-26T06_48_23_590Z-
27 verbose logfile /Users/aaa/.npm/_logs/2023-07-26T06_48_23_590Z-debug-0.log
28 timing npm:load:logFile Completed in 2ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 39ms
32 timing command:config Completed in 1ms
33 verbose stack Error: This command does not support workspaces.
33 verbose stack     at Config.cmdExec (/Users/aaa/.nvm/versions/node/v18.16.0/lib/node_modules/npm/lib/base-command.js:123:29)
33 verbose stack     at Npm.exec (/Users/aaa/.nvm/versions/node/v18.16.0/lib/node_modules/npm/lib/npm.js:154:20)
33 verbose stack     at async module.exports (/Users/aaa/.nvm/versions/node/v18.16.0/lib/node_modules/npm/lib/cli.js:134:5)
34 verbose cwd /Users/aaa/hacking/union-mono/libs/wealthy-editor
35 verbose Darwin 21.4.0
36 verbose node v18.16.0
37 verbose npm  v9.5.1
38 error code ENOWORKSPACES
39 error This command does not support workspaces.
40 verbose exit 1
41 timing npm Completed in 50ms
42 verbose code 1
43 error A complete log of this run can be found in:
43 error     /Users/aaa/.npm/_logs/2023-07-26T06_48_23_590Z-debug-0.log
```

**Comment by romkatv** [comment]
How is this related to powerlevel10k?
